-- ============================================================================
--  V10_0  QUICK CHECK - every table and column Section 10 reads (run first)
--  Version   : 1.0 (2026-10-07)        Run log: 06_Run_Results/RUN_LOG.md
--  For: F10.1, F10.2, F10.3 and V10_1 (Section 10 block v1.0)
--  NOT CHECKED HERE: ESS_REQUEST_HISTORY (PROCESSSTART, REQUESTID, REQUESTTYPE,
--  STATE, SUBMISSION). The data dictionary shows no column for it (R016), so a
--  dictionary check would always say NOT VISIBLE; all five are proven by reads
--  (R034 SELECT *, R035 by name). DBMS_UTILITY.PORT_STRING is a function, not
--  an object: V10_2d tests it.
--
--  The statement below the header is GENERATED by
--    python3 07_Dev_Tools/colrefs.py --v0 "V10_0 v1.0 (Section 10 block v1.0)"
--        --cand '<pattern below>' --skip ESS_REQUEST_HISTORY
--        F10.1 F10.2 F10.3 V10_1
--  ord 0 prints this version and "14 objects / 56 columns needed"; every
--  object row says "N needed".
--
--  READING IT
--    ord 1-14   every row must say ALL OK. Rows 1, 2 and 9 (AD_PRODUCT_GROUPS,
--               PRODUCT_COMPONENT_VERSION, NLS_DATABASE_PARAMETERS) are the
--               risky ones; their read tests V10_2a / V10_2c / V10_2b decide
--               even if the dictionary says NOT VISIBLE (it is blind to some
--               readable objects: ESS, R016 / R034).
--    ord 50+    CANDIDATES, not used by any query: the objects behind the EBS
--               rows Fusion fills with "Oracle-managed (SaaS)" (V_$DATABASE,
--               V_$PARAMETER, GV_$INSTANCE, V_$DATAGUARD_CONFIG, V_$OPTION,
--               V_$RMAN_BACKUP_JOB_DETAILS, DBA_DATA_FILES / TEMP_FILES /
--               SEGMENTS / TABLESPACES / FEATURE_USAGE_STATISTICS), the release
--               and patch candidates (AD_*, PATCH_*, FND_PRODUCT_GROUPS,
--               ALL_REGISTRY_BANNERS, V_$VERSION, V_$INSTANCE) and ASK_DEPLOYED_*
--               (pod URLs). A SYS view is listed only if the report user can
--               read it; a DBA_ name always shows its PUBLIC synonym, so read
--               its "columns_present": "-" = the view behind it is not readable.
--    Pattern: ^(AD_.+|PATCH_.+|ASK_DEPLOYED_.+|FND_PRODUCT_GROUPS|ALL_REGISTRY_
--             BANNERS|V_$(DATABASE|INSTANCE|PARAMETER|OPTION|VERSION|DATAGUARD_
--             CONFIG|RMAN_BACKUP_JOB_DETAILS)|GV_$INSTANCE|DBA_(DATA_FILES|TEMP_
--             FILES|SEGMENTS|TABLESPACES|FEATURE_USAGE_STATISTICS))$
--
--  OUTPUT  ord | object_name | needed_count | needed_columns | type_flags |
--          visible_as | columns_present
--  Metadata only (ALL_OBJECTS, ALL_SYNONYMS, ALL_TAB_COLUMNS). No binds. Pure
--  SELECT. Nothing is written.
-- ============================================================================
WITH
need AS (
    SELECT  1 AS ord, 'AD_PRODUCT_GROUPS' AS tab, 'LAST_UPDATE_DATE' AS col FROM dual
    UNION ALL SELECT  1, 'AD_PRODUCT_GROUPS', 'RELEASE_NAME' FROM dual
    UNION ALL SELECT  2, 'PRODUCT_COMPONENT_VERSION', 'PRODUCT' FROM dual
    UNION ALL SELECT  2, 'PRODUCT_COMPONENT_VERSION', 'VERSION' FROM dual
    UNION ALL SELECT  2, 'PRODUCT_COMPONENT_VERSION', 'VERSION_FULL' FROM dual
    UNION ALL SELECT  3, 'FND_LANGUAGES_B', 'ACTIVATION_STATUS' FROM dual
    UNION ALL SELECT  3, 'FND_LANGUAGES_B', 'INSTALLED_FLAG' FROM dual
    UNION ALL SELECT  3, 'FND_LANGUAGES_B', 'LANGUAGE_CODE' FROM dual
    UNION ALL SELECT  3, 'FND_LANGUAGES_B', 'NLS_LANGUAGE' FROM dual
    UNION ALL SELECT  4, 'FND_LANGUAGES_TL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT  4, 'FND_LANGUAGES_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT  4, 'FND_LANGUAGES_TL', 'LANGUAGE_CODE' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'ENTERPRISE_ID' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'HIERARCHY_NAME' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'ORA_SEED_SET1' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'ORA_SEED_SET2' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'PROFILE_OPTION_ID' FROM dual
    UNION ALL SELECT  5, 'FND_PROFILE_OPTIONS_B', 'PROFILE_OPTION_NAME' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'ENTERPRISE_ID' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'LAST_UPDATE_DATE' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'LEVEL_NAME' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'LEVEL_VALUE' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'ORA_SEED_SET1' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'ORA_SEED_SET2' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'PROFILE_OPTION_ID' FROM dual
    UNION ALL SELECT  6, 'FND_PROFILE_OPTION_VALUES', 'PROFILE_OPTION_VALUE' FROM dual
    UNION ALL SELECT  7, 'FND_TIMEZONES_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT  7, 'FND_TIMEZONES_TL', 'NAME' FROM dual
    UNION ALL SELECT  7, 'FND_TIMEZONES_TL', 'TIMEZONE_CODE' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'CREATED_BY' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'CREATION_DATE' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'LAST_UPDATE_DATE' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'NAME' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'PRIVATE_FLAG' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'PUBLISH_DATE' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'PUBLISH_FLAG' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'SANDBOX_ID' FROM dual
    UNION ALL SELECT  8, 'ADF_SB_SANDBOXES', 'SANDBOX_STATE' FROM dual
    UNION ALL SELECT  9, 'NLS_DATABASE_PARAMETERS', 'PARAMETER' FROM dual
    UNION ALL SELECT  9, 'NLS_DATABASE_PARAMETERS', 'VALUE' FROM dual
    UNION ALL SELECT 10, 'FND_LOOKUP_VALUES', 'LANGUAGE' FROM dual
    UNION ALL SELECT 10, 'FND_LOOKUP_VALUES', 'LOOKUP_CODE' FROM dual
    UNION ALL SELECT 10, 'FND_LOOKUP_VALUES', 'LOOKUP_TYPE' FROM dual
    UNION ALL SELECT 10, 'FND_LOOKUP_VALUES', 'MEANING' FROM dual
    UNION ALL SELECT 11, 'FUN_ALL_BUSINESS_UNITS_V', 'BU_ID' FROM dual
    UNION ALL SELECT 11, 'FUN_ALL_BUSINESS_UNITS_V', 'PRIMARY_LEDGER_ID' FROM dual
    UNION ALL SELECT 11, 'FUN_ALL_BUSINESS_UNITS_V', 'STATUS' FROM dual
    UNION ALL SELECT 12, 'GL_LEDGERS', 'COMPLETE_FLAG' FROM dual
    UNION ALL SELECT 12, 'GL_LEDGERS', 'LEDGER_ID' FROM dual
    UNION ALL SELECT 12, 'GL_LEDGERS', 'OBJECT_TYPE_CODE' FROM dual
    UNION ALL SELECT 13, 'INV_ORGANIZATION_DEFINITIONS_V', 'ORGANIZATION_ID' FROM dual
    UNION ALL SELECT 13, 'INV_ORGANIZATION_DEFINITIONS_V', 'SET_OF_BOOKS_ID' FROM dual
    UNION ALL SELECT 14, 'FA_BOOK_CONTROLS', 'BOOK_TYPE_CODE' FROM dual
    UNION ALL SELECT 14, 'FA_BOOK_CONTROLS', 'SET_OF_BOOKS_ID' FROM dual
),
need_tab AS (
    SELECT n.ord, n.tab FROM need n GROUP BY n.ord, n.tab
),
-- totals for the ord 0 version row (one aggregate per CTE)
need_tab_cnt AS (
    SELECT COUNT(*) AS n FROM need_tab
),
need_col_cnt AS (
    SELECT COUNT(*) AS n FROM need
),
need_obj AS (
    SELECT o.object_name AS tab,
           LISTAGG(o.owner || '.' || o.object_type, ', ')
               WITHIN GROUP (ORDER BY o.owner, o.object_type)   AS visible_as
    FROM   all_objects o
    WHERE  o.object_name IN ( SELECT n.tab FROM need_tab n )
    GROUP  BY o.object_name
),
-- ---- candidate block: visible objects named like the --cand pattern
cand_obj AS (
    SELECT o.object_name AS tab,
           LISTAGG(o.owner || '.' || o.object_type, ', ')
               WITHIN GROUP (ORDER BY o.owner, o.object_type)   AS visible_as
    FROM   all_objects o
    WHERE  o.object_type IN ('TABLE', 'VIEW', 'SYNONYM')
    AND    REGEXP_LIKE(o.object_name, '^(AD_.+|PATCH_.+|ASK_DEPLOYED_.+|FND_PRODUCT_GROUPS|ALL_REGISTRY_BANNERS|V_\$(DATABASE|INSTANCE|PARAMETER|OPTION|VERSION|DATAGUARD_CONFIG|RMAN_BACKUP_JOB_DETAILS)|GV_\$INSTANCE|DBA_(DATA_FILES|TEMP_FILES|SEGMENTS|TABLESPACES|FEATURE_USAGE_STATISTICS))$')
    AND    o.object_name NOT IN ( SELECT n.tab FROM need_tab n )
    GROUP  BY o.object_name
),
cand_cnt AS (
    SELECT COUNT(*) AS n FROM cand_obj
),
cand_rows AS (
    SELECT c.tab, c.visible_as,
           ROW_NUMBER() OVER (ORDER BY c.tab) AS rn
    FROM   cand_obj c
),
all_names AS (
    SELECT n.tab FROM need_tab n
    UNION ALL
    SELECT c.tab FROM cand_obj c
),
-- a name that is only a synonym has its columns under the synonym's target
syn AS (
    SELECT s.synonym_name,
           MAX(s.table_name)                         AS target_tab,
           MAX(s.table_owner || '.' || s.table_name) AS target_full
    FROM   all_synonyms s
    WHERE  s.synonym_name IN ( SELECT a.tab FROM all_names a )
    GROUP  BY s.synonym_name
),
cols AS (
    SELECT c.table_name, c.column_name, MAX(c.data_type) AS data_type
    FROM   all_tab_columns c
    WHERE  c.table_name IN ( SELECT a.tab FROM all_names a )
    OR     c.table_name IN ( SELECT s.target_tab FROM syn s )
    GROUP  BY c.table_name, c.column_name
),
tab_has AS (
    SELECT c.table_name FROM cols c GROUP BY c.table_name
),
resolved AS (
    SELECT a.tab,
           CASE WHEN th.table_name IS NOT NULL THEN a.tab ELSE s.target_tab END AS col_tab,
           s.target_full
    FROM        all_names a
    LEFT JOIN   tab_has   th ON th.table_name   = a.tab
    LEFT JOIN   syn       s  ON s.synonym_name  = a.tab
),
need_check AS (
    SELECT  n.ord, n.tab,
            COUNT(*)                                          AS n_needed,
            LISTAGG(CASE WHEN c.column_name IS NULL THEN n.col END, ', ')
                WITHIN GROUP (ORDER BY n.col)                 AS missing,
            LISTAGG(CASE WHEN c.data_type IN ('NVARCHAR2', 'NCHAR', 'NCLOB',
                                              'CLOB', 'BLOB', 'LONG')
                         THEN n.col || ' ' || c.data_type END, ', ')
                WITHIN GROUP (ORDER BY n.col)                 AS type_flags
    FROM        need     n
    JOIN        resolved r ON r.tab = n.tab
    LEFT JOIN   cols     c ON c.table_name = r.col_tab AND c.column_name = n.col
    GROUP   BY  n.ord, n.tab
),
col_lists AS (
    SELECT  c.table_name,
            LISTAGG(c.column_name, ' ' ON OVERFLOW TRUNCATE)
                WITHIN GROUP (ORDER BY c.column_name)         AS col_list
    FROM    cols c
    GROUP   BY c.table_name
),
grid AS (
    SELECT  nc.ord                                                    AS ord,
            CAST(nc.tab AS VARCHAR2(400))                             AS object_name,
            CAST(nc.n_needed || ' needed' AS VARCHAR2(400))           AS needed_count,
            CAST(CASE WHEN r.col_tab IS NULL OR cl.table_name IS NULL
                      THEN '*** OBJECT NOT VISIBLE ***'
                      WHEN nc.missing IS NULL THEN 'ALL OK'
                      ELSE '*** MISSING: ' || nc.missing || ' ***'
                 END AS VARCHAR2(4000))                               AS needed_columns,
            CAST(NVL(nc.type_flags, '-') AS VARCHAR2(4000))           AS type_flags,
            CAST(NVL(nob.visible_as, '-')
                 || CASE WHEN r.col_tab <> nc.tab
                         THEN ' (columns read from ' || r.target_full || ')' END
                 AS VARCHAR2(4000))                                   AS visible_as,
            CAST(NVL(cl.col_list, '-') AS VARCHAR2(4000))             AS columns_present
    FROM        need_check nc
    JOIN        resolved   r  ON r.tab  = nc.tab
    LEFT JOIN   need_obj   nob ON nob.tab = nc.tab
    LEFT JOIN   col_lists  cl ON cl.table_name = r.col_tab
    UNION ALL
    SELECT  0,
            TO_CHAR('V10_0 v1.0 (Section 10 block v1.0)'),
            TO_CHAR(nt.n || ' objects / ' || ncc.n || ' columns needed'),
            TO_CHAR('VERSION ROW: compare this line with the query header'),
            TO_CHAR('-'),
            TO_CHAR('-'),
            TO_CHAR('-')
    FROM    need_tab_cnt nt CROSS JOIN need_col_cnt ncc
    UNION ALL
    SELECT  50,
            TO_CHAR('CANDIDATES'),
            TO_CHAR('-'),
            TO_CHAR('INFO: ' || cc.n || ' candidate object(s) visible (name matches ^(AD_.+|PATCH_.+|ASK_DEPLOYED_.+|FND_PRODUCT_GROUPS|ALL_REGISTRY_BANNERS|V_\$(DATABASE|INSTANCE|PARAMETER|OPTION|VERSION|DATAGUARD_CONFIG|RMAN_BACKUP_JOB_DETAILS)|GV_\$INSTANCE|DBA_(DATA_FILES|TEMP_FILES|SEGMENTS|TABLESPACES|FEATURE_USAGE_STATISTICS))$);'
                    || ' up to 60 listed below. 0 = none visible.'),
            TO_CHAR('-'),
            TO_CHAR('-'),
            TO_CHAR('-')
    FROM    cand_cnt cc
    UNION ALL
    SELECT  50 + cr.rn,
            TO_CHAR(cr.tab),
            TO_CHAR('-'),
            TO_CHAR('CANDIDATE: not used by any query yet'),
            TO_CHAR('-'),
            TO_CHAR(cr.visible_as
                    || CASE WHEN r.col_tab <> cr.tab
                            THEN ' (columns read from ' || r.target_full || ')' END),
            TO_CHAR(NVL(cl.col_list, '-'))
    FROM        cand_rows  cr
    JOIN        resolved   r  ON r.tab = cr.tab
    LEFT JOIN   col_lists  cl ON cl.table_name = r.col_tab
    WHERE       cr.rn <= 60
)
SELECT  g.ord              AS ord,
        g.object_name      AS object_name,
        g.needed_count     AS needed_count,
        g.needed_columns   AS needed_columns,
        g.type_flags       AS type_flags,
        g.visible_as       AS visible_as,
        g.columns_present  AS columns_present
FROM    grid g
ORDER BY g.ord
