-- ============================================================================
--  V3_1  QUICK CHECK - every table and column the Section 3 workbooks and
--        Section 3.2 read (run FIRST, after V3_0)
--  Version   : 1.0 (2026-10-05)        Run log: 06_Run_Results/RUN_LOG.md
--  For: F3.1_WB_Payment_Terms_AP / _AR, F3.1_WB_Setup_01 .. 10,
--       F3.2_DFF_Deep_Dive, F3.2_WB_Descriptive_Flexfields
--
--  Every name below was checked on the Oracle Fusion Tables and Views pages
--  (2026-10-05) or by an earlier pod run. This proves them on THIS pod, so a
--  wrong or ungranted name shows up as a row here instead of as ORA-00904 /
--  ORA-00942. Metadata only (ALL_TAB_COLUMNS) - it cannot fail.
--
--  OUTPUT  ord | object_name | needed_columns | columns_present
--    needed_columns = 'ALL OK', '*** MISSING: <cols> ***' or
--                     '*** OBJECT NOT VISIBLE ***'
--  Every row must say ALL OK. Paste the grid back (columns_present is cut at
--  4,000 characters for wide tables - that is expected).
--  No binds. Pure SELECT. Nothing is written.
-- ============================================================================
WITH
need AS (
    SELECT  1 AS ord, 'AP_TERMS_B' AS tab, 'TERM_ID' AS col FROM dual
    UNION ALL SELECT  1, 'AP_TERMS_B', 'TYPE' FROM dual
    UNION ALL SELECT  1, 'AP_TERMS_B', 'ENABLED_FLAG' FROM dual
    UNION ALL SELECT  1, 'AP_TERMS_B', 'START_DATE_ACTIVE' FROM dual
    UNION ALL SELECT  1, 'AP_TERMS_B', 'END_DATE_ACTIVE' FROM dual
    UNION ALL SELECT  1, 'AP_TERMS_B', 'DUE_CUTOFF_DAY' FROM dual
    UNION ALL SELECT  2, 'AP_TERMS_TL', 'TERM_ID' FROM dual
    UNION ALL SELECT  2, 'AP_TERMS_TL', 'NAME' FROM dual
    UNION ALL SELECT  2, 'AP_TERMS_TL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT  2, 'AP_TERMS_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'TERM_ID' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'SEQUENCE_NUM' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'DUE_DAYS' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'DUE_DAY_OF_MONTH' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'DUE_MONTHS_FORWARD' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'DISCOUNT_PERCENT' FROM dual
    UNION ALL SELECT  3, 'AP_TERMS_LINES', 'DISCOUNT_DAYS' FROM dual
    UNION ALL SELECT  4, 'AP_INVOICES_ALL', 'TERMS_ID' FROM dual
    UNION ALL SELECT  5, 'PO_HEADERS_ALL', 'TERMS_ID' FROM dual
    UNION ALL SELECT  6, 'POZ_SUPPLIER_SITES_ALL_M', 'TERMS_ID' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'TERM_ID' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'NAME' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'DESCRIPTION' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'SET_ID' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'START_DATE_ACTIVE' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'END_DATE_ACTIVE' FROM dual
    UNION ALL SELECT  7, 'RA_TERMS_B', 'DUE_CUTOFF_DAY' FROM dual
    UNION ALL SELECT  8, 'RA_TERMS_LINES', 'TERM_ID' FROM dual
    UNION ALL SELECT  8, 'RA_TERMS_LINES', 'SEQUENCE_NUM' FROM dual
    UNION ALL SELECT  8, 'RA_TERMS_LINES', 'DUE_DAYS' FROM dual
    UNION ALL SELECT  8, 'RA_TERMS_LINES', 'DUE_DAY_OF_MONTH' FROM dual
    UNION ALL SELECT  8, 'RA_TERMS_LINES', 'DUE_MONTHS_FORWARD' FROM dual
    UNION ALL SELECT  9, 'RA_TERMS_LINES_DISCOUNTS', 'TERM_ID' FROM dual
    UNION ALL SELECT  9, 'RA_TERMS_LINES_DISCOUNTS', 'SEQUENCE_NUM' FROM dual
    UNION ALL SELECT  9, 'RA_TERMS_LINES_DISCOUNTS', 'DISCOUNT_PERCENT' FROM dual
    UNION ALL SELECT  9, 'RA_TERMS_LINES_DISCOUNTS', 'DISCOUNT_DAYS' FROM dual
    UNION ALL SELECT 10, 'RA_CUSTOMER_TRX_ALL', 'TERM_ID' FROM dual
    UNION ALL SELECT 11, 'HZ_CUST_SITE_USES_ALL', 'PAYMENT_TERM_ID' FROM dual
    UNION ALL SELECT 12, 'HZ_CUSTOMER_PROFILES_F', 'STANDARD_TERMS' FROM dual
    UNION ALL SELECT 12, 'HZ_CUSTOMER_PROFILES_F', 'EFFECTIVE_START_DATE' FROM dual
    UNION ALL SELECT 12, 'HZ_CUSTOMER_PROFILES_F', 'EFFECTIVE_END_DATE' FROM dual
    UNION ALL SELECT 13, 'FND_SETID_SETS_VL', 'SET_ID' FROM dual
    UNION ALL SELECT 13, 'FND_SETID_SETS_VL', 'SET_CODE' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'NAME' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'TYPE' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'STATUS' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'POST_TO_GL' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'ACCOUNTING_AFFECT_FLAG' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'START_DATE' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'END_DATE' FROM dual
    UNION ALL SELECT 14, 'RA_CUST_TRX_TYPES_ALL', 'SET_ID' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'NAME' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'STATUS' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'BATCH_SOURCE_TYPE' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'START_DATE' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'END_DATE' FROM dual
    UNION ALL SELECT 15, 'RA_BATCH_SOURCES_ALL', 'SET_ID' FROM dual
    UNION ALL SELECT 16, 'GL_JE_SOURCES_TL', 'JE_SOURCE_NAME' FROM dual
    UNION ALL SELECT 16, 'GL_JE_SOURCES_TL', 'USER_JE_SOURCE_NAME' FROM dual
    UNION ALL SELECT 16, 'GL_JE_SOURCES_TL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 16, 'GL_JE_SOURCES_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 17, 'GL_JE_SOURCES_B', 'JE_SOURCE_NAME' FROM dual
    UNION ALL SELECT 17, 'GL_JE_SOURCES_B', 'JOURNAL_APPROVAL_FLAG' FROM dual
    UNION ALL SELECT 17, 'GL_JE_SOURCES_B', 'IMPORT_USING_KEY_FLAG' FROM dual
    UNION ALL SELECT 18, 'GL_JE_CATEGORIES_TL', 'JE_CATEGORY_NAME' FROM dual
    UNION ALL SELECT 18, 'GL_JE_CATEGORIES_TL', 'USER_JE_CATEGORY_NAME' FROM dual
    UNION ALL SELECT 18, 'GL_JE_CATEGORIES_TL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 18, 'GL_JE_CATEGORIES_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 19, 'GL_JE_CATEGORIES_B', 'JE_CATEGORY_NAME' FROM dual
    UNION ALL SELECT 19, 'GL_JE_CATEGORIES_B', 'CONSOLIDATION_FLAG' FROM dual
    UNION ALL SELECT 19, 'GL_JE_CATEGORIES_B', 'DISALLOW_MJE_FLAG' FROM dual
    UNION ALL SELECT 20, 'GL_JE_HEADERS', 'JE_SOURCE' FROM dual
    UNION ALL SELECT 20, 'GL_JE_HEADERS', 'JE_CATEGORY' FROM dual
    UNION ALL SELECT 20, 'GL_JE_HEADERS', 'LEDGER_ID' FROM dual
    UNION ALL SELECT 21, 'PO_DOCUMENT_TYPES_ALL_B', 'DOCUMENT_TYPE_CODE' FROM dual
    UNION ALL SELECT 21, 'PO_DOCUMENT_TYPES_ALL_B', 'DOCUMENT_SUBTYPE' FROM dual
    UNION ALL SELECT 21, 'PO_DOCUMENT_TYPES_ALL_B', 'PRC_BU_ID' FROM dual
    UNION ALL SELECT 22, 'PO_DOCUMENT_TYPES_ALL_TL', 'DOCUMENT_TYPE_CODE' FROM dual
    UNION ALL SELECT 22, 'PO_DOCUMENT_TYPES_ALL_TL', 'DOCUMENT_SUBTYPE' FROM dual
    UNION ALL SELECT 22, 'PO_DOCUMENT_TYPES_ALL_TL', 'PRC_BU_ID' FROM dual
    UNION ALL SELECT 22, 'PO_DOCUMENT_TYPES_ALL_TL', 'TYPE_NAME' FROM dual
    UNION ALL SELECT 22, 'PO_DOCUMENT_TYPES_ALL_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 23, 'FUN_ALL_BUSINESS_UNITS_V', 'BU_ID' FROM dual
    UNION ALL SELECT 23, 'FUN_ALL_BUSINESS_UNITS_V', 'BU_NAME' FROM dual
    UNION ALL SELECT 23, 'FUN_ALL_BUSINESS_UNITS_V', 'PRIMARY_LEDGER_ID' FROM dual
    UNION ALL SELECT 23, 'FUN_ALL_BUSINESS_UNITS_V', 'STATUS' FROM dual
    UNION ALL SELECT 24, 'EGP_SYSTEM_ITEMS_B', 'INVENTORY_ITEM_ID' FROM dual
    UNION ALL SELECT 24, 'EGP_SYSTEM_ITEMS_B', 'ITEM_NUMBER' FROM dual
    UNION ALL SELECT 24, 'EGP_SYSTEM_ITEMS_B', 'TEMPLATE_ITEM_FLAG' FROM dual
    UNION ALL SELECT 25, 'EGP_SYSTEM_ITEMS_TL', 'INVENTORY_ITEM_ID' FROM dual
    UNION ALL SELECT 25, 'EGP_SYSTEM_ITEMS_TL', 'ORGANIZATION_ID' FROM dual
    UNION ALL SELECT 25, 'EGP_SYSTEM_ITEMS_TL', 'TEMPLATE_NAME' FROM dual
    UNION ALL SELECT 25, 'EGP_SYSTEM_ITEMS_TL', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 25, 'EGP_SYSTEM_ITEMS_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'SECONDARY_INVENTORY_NAME' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'ORGANIZATION_ID' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'ASSET_INVENTORY' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'QUANTITY_TRACKED' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'LOCATOR_TYPE' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'PICKING_ORDER' FROM dual
    UNION ALL SELECT 26, 'INV_SECONDARY_INVENTORIES', 'DISABLE_DATE' FROM dual
    UNION ALL SELECT 27, 'INV_ORGANIZATION_DEFINITIONS_V', 'ORGANIZATION_ID' FROM dual
    UNION ALL SELECT 27, 'INV_ORGANIZATION_DEFINITIONS_V', 'ORGANIZATION_CODE' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'BANK_ACCOUNT_ID' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'BANK_ACCOUNT_NAME' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'DESCRIPTION' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'CURRENCY_CODE' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'MASKED_ACCOUNT_NUM' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'END_DATE' FROM dual
    UNION ALL SELECT 28, 'CE_BANK_ACCOUNTS', 'ACCOUNT_CLASSIFICATION' FROM dual
    UNION ALL SELECT 29, 'CE_BANK_ACCT_USES_ALL', 'BANK_ACCOUNT_ID' FROM dual
    UNION ALL SELECT 29, 'CE_BANK_ACCT_USES_ALL', 'ORG_ID' FROM dual
    UNION ALL SELECT 30, 'CST_COST_BOOKS_B', 'COST_BOOK_ID' FROM dual
    UNION ALL SELECT 30, 'CST_COST_BOOKS_B', 'COST_BOOK_CODE' FROM dual
    UNION ALL SELECT 30, 'CST_COST_BOOKS_B', 'PERIODIC_AVERAGE_FLAG' FROM dual
    UNION ALL SELECT 31, 'FA_BOOK_CONTROLS', 'BOOK_TYPE_CODE' FROM dual
    UNION ALL SELECT 31, 'FA_BOOK_CONTROLS', 'BOOK_CLASS' FROM dual
    UNION ALL SELECT 31, 'FA_BOOK_CONTROLS', 'DATE_INEFFECTIVE' FROM dual
    UNION ALL SELECT 31, 'FA_BOOK_CONTROLS', 'DISTRIBUTION_SOURCE_BOOK' FROM dual
    UNION ALL SELECT 31, 'FA_BOOK_CONTROLS', 'SET_OF_BOOKS_ID' FROM dual
    UNION ALL SELECT 31, 'FA_BOOK_CONTROLS', 'GL_POSTING_ALLOWED_FLAG' FROM dual
    UNION ALL SELECT 32, 'GL_LEDGERS', 'LEDGER_ID' FROM dual
    UNION ALL SELECT 32, 'GL_LEDGERS', 'NAME' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'DESCRIPTIVE_FLEXFIELD_CODE' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'CONTEXT_CODE' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'SEGMENT_CODE' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'COLUMN_NAME' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'SEQUENCE_NUMBER' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'ENABLED_FLAG' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'REQUIRED_FLAG' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'VALUE_SET_ID' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'DISPLAY_TYPE' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'DISPLAY_WIDTH' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'CREATED_BY' FROM dual
    UNION ALL SELECT 33, 'FND_DF_SEGMENTS_B', 'LAST_UPDATED_BY' FROM dual
    UNION ALL SELECT 34, 'FND_DF_SEGMENTS_TL', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT 34, 'FND_DF_SEGMENTS_TL', 'DESCRIPTIVE_FLEXFIELD_CODE' FROM dual
    UNION ALL SELECT 34, 'FND_DF_SEGMENTS_TL', 'CONTEXT_CODE' FROM dual
    UNION ALL SELECT 34, 'FND_DF_SEGMENTS_TL', 'SEGMENT_CODE' FROM dual
    UNION ALL SELECT 34, 'FND_DF_SEGMENTS_TL', 'PROMPT' FROM dual
    UNION ALL SELECT 34, 'FND_DF_SEGMENTS_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 35, 'FND_DF_CONTEXTS_TL', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT 35, 'FND_DF_CONTEXTS_TL', 'DESCRIPTIVE_FLEXFIELD_CODE' FROM dual
    UNION ALL SELECT 35, 'FND_DF_CONTEXTS_TL', 'CONTEXT_CODE' FROM dual
    UNION ALL SELECT 35, 'FND_DF_CONTEXTS_TL', 'NAME' FROM dual
    UNION ALL SELECT 35, 'FND_DF_CONTEXTS_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 36, 'FND_DF_FLEXFIELDS_TL', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT 36, 'FND_DF_FLEXFIELDS_TL', 'DESCRIPTIVE_FLEXFIELD_CODE' FROM dual
    UNION ALL SELECT 36, 'FND_DF_FLEXFIELDS_TL', 'NAME' FROM dual
    UNION ALL SELECT 36, 'FND_DF_FLEXFIELDS_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT 37, 'FND_DESCRIPTIVE_FLEXS', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT 37, 'FND_DESCRIPTIVE_FLEXS', 'DESCRIPTIVE_FLEXFIELD_NAME' FROM dual
    UNION ALL SELECT 37, 'FND_DESCRIPTIVE_FLEXS', 'APPLICATION_TABLE_NAME' FROM dual
    UNION ALL SELECT 38, 'FND_FLEX_VALUE_SETS', 'FLEX_VALUE_SET_ID' FROM dual
    UNION ALL SELECT 38, 'FND_FLEX_VALUE_SETS', 'FLEX_VALUE_SET_NAME' FROM dual
    UNION ALL SELECT 39, 'PER_USERS', 'USERNAME' FROM dual
    UNION ALL SELECT 40, 'FND_TABLES', 'TABLE_NAME' FROM dual
    UNION ALL SELECT 40, 'FND_TABLES', 'PHYSICAL_TABLE_NAME' FROM dual
    UNION ALL SELECT 40, 'FND_TABLES', 'APPLICATION_SHORT_NAME' FROM dual
    UNION ALL SELECT 41, 'FND_APPLICATION_VL', 'APPLICATION_ID' FROM dual
    UNION ALL SELECT 41, 'FND_APPLICATION_VL', 'APPLICATION_SHORT_NAME' FROM dual
    UNION ALL SELECT 41, 'FND_APPLICATION_VL', 'APPLICATION_NAME' FROM dual
),
cols AS (
    SELECT  c.table_name, c.column_name
    FROM    all_tab_columns c
    WHERE   c.table_name IN ( SELECT n.tab FROM need n )
    GROUP   BY c.table_name, c.column_name
),
need_check AS (
    SELECT  n.ord, n.tab,
            LISTAGG(CASE WHEN c.column_name IS NULL THEN n.col END, ', ')
                WITHIN GROUP (ORDER BY n.col)                 AS missing
    FROM        need n
    LEFT JOIN   cols c ON c.table_name = n.tab AND c.column_name = n.col
    GROUP   BY  n.ord, n.tab
),
all_cols AS (
    SELECT  table_name,
            LISTAGG(column_name, ' ' ON OVERFLOW TRUNCATE)
                WITHIN GROUP (ORDER BY column_name)           AS col_list
    FROM    cols
    GROUP   BY table_name
)
SELECT  nc.ord                                              AS ord,
        nc.tab                                              AS object_name,
        CASE WHEN a.table_name IS NULL THEN '*** OBJECT NOT VISIBLE ***'
             WHEN nc.missing IS NULL   THEN 'ALL OK'
             ELSE '*** MISSING: ' || nc.missing || ' ***'
        END                                                 AS needed_columns,
        NVL(a.col_list, '-')                                AS columns_present
FROM        need_check nc
LEFT JOIN   all_cols   a ON a.table_name = nc.tab
ORDER BY    nc.ord
