-- ============================================================================
--  V8_0  QUICK CHECK - every table and column Section 8 v1.1 reads
--  Version   : 1.1 (2026-10-06)        Run log: 06_Run_Results/RUN_LOG.md
--              v1.1: regenerated for Section 8 block v1.1 (F8.1, F8.2a, F8.2b,
--              F8.2c, F8.2_WB1, F8.2_WB2, V8_1 v1.1): 10 objects / 28 columns.
--              Adds GL_FRC_REPORTS_TL (proven by R031's candidate list) and
--              FND_APPLICATION_VL (proven by R003); drops LAST_ACCESSED_DATE
--              (R033: it equals LAST_MODIFIED_DATE). NO RE-RUN NEEDED on this
--              pod: every column below was printed by R031 or R003.
--              v1.0 ran as R031 (9 / 9 ALL OK).
--  NOT CHECKED HERE: ESS_REQUEST_HISTORY (DEFINITION, JOBTYPE, NAME,
--  PROCESSSTART, PRODUCT, SUBMITTER). The data dictionary shows no column for
--  it (R016), so a dictionary check would always say NOT VISIBLE. Those six
--  columns are proven by reads instead: R034 (V5_2a, SELECT *) and R035 (V8_3,
--  by name).
--
--  The statement below the header is GENERATED by
--    python3 07_Dev_Tools/colrefs.py --v0 "V8_0 v1.1 (Section 8 block v1.1)"
--        --skip ESS_REQUEST_HISTORY <the seven files above>
--  ord 0 prints this version and "10 objects / 28 columns needed"; every
--  object row says "N needed".
--
--  OUTPUT  ord | object_name | needed_count | needed_columns | type_flags |
--          visible_as | columns_present
--  Every object row (ord 1-10) must say ALL OK. Metadata only (ALL_OBJECTS,
--  ALL_SYNONYMS, ALL_TAB_COLUMNS). No binds. Pure SELECT. Nothing is written.
-- ============================================================================
WITH
need AS (
    SELECT  1 AS ord, 'GL_FRC_REPORTS_B' AS tab, 'AUTHOR_DISPLAY_NAME' AS col FROM dual
    UNION ALL SELECT  1, 'GL_FRC_REPORTS_B', 'BIP_REPORT_JOB_DEFINITION' FROM dual
    UNION ALL SELECT  1, 'GL_FRC_REPORTS_B', 'LAST_MODIFIED_DATE' FROM dual
    UNION ALL SELECT  1, 'GL_FRC_REPORTS_B', 'LAST_UPDATE_DATE' FROM dual
    UNION ALL SELECT  1, 'GL_FRC_REPORTS_B', 'REPORT_ID' FROM dual
    UNION ALL SELECT  1, 'GL_FRC_REPORTS_B', 'REPORT_PATH' FROM dual
    UNION ALL SELECT  1, 'GL_FRC_REPORTS_B', 'REPORT_TYPE_CODE' FROM dual
    UNION ALL SELECT  2, 'GL_FRC_REPORTS_TL', 'LANGUAGE' FROM dual
    UNION ALL SELECT  2, 'GL_FRC_REPORTS_TL', 'REPORT_DISPLAY_NAME' FROM dual
    UNION ALL SELECT  2, 'GL_FRC_REPORTS_TL', 'REPORT_ID' FROM dual
    UNION ALL SELECT  3, 'GL_FRC_USER_ACCESS_REPORTS', 'LAST_ACCESSED_DATE' FROM dual
    UNION ALL SELECT  3, 'GL_FRC_USER_ACCESS_REPORTS', 'REPORT_ID' FROM dual
    UNION ALL SELECT  3, 'GL_FRC_USER_ACCESS_REPORTS', 'USER_NAME' FROM dual
    UNION ALL SELECT  4, 'GL_ACCOUNT_GROUPS', 'ACCOUNT_GROUP_ID' FROM dual
    UNION ALL SELECT  5, 'GL_ACCOUNT_GROUP_DETAILS', 'ACCOUNT_GROUP_ID' FROM dual
    UNION ALL SELECT  5, 'GL_ACCOUNT_GROUP_DETAILS', 'LEDGER_ID' FROM dual
    UNION ALL SELECT  6, 'FND_APPLICATION_VL', 'APPLICATION_NAME' FROM dual
    UNION ALL SELECT  6, 'FND_APPLICATION_VL', 'APPLICATION_SHORT_NAME' FROM dual
    UNION ALL SELECT  7, 'FUN_ALL_BUSINESS_UNITS_V', 'BU_ID' FROM dual
    UNION ALL SELECT  7, 'FUN_ALL_BUSINESS_UNITS_V', 'PRIMARY_LEDGER_ID' FROM dual
    UNION ALL SELECT  7, 'FUN_ALL_BUSINESS_UNITS_V', 'STATUS' FROM dual
    UNION ALL SELECT  8, 'GL_LEDGERS', 'COMPLETE_FLAG' FROM dual
    UNION ALL SELECT  8, 'GL_LEDGERS', 'LEDGER_ID' FROM dual
    UNION ALL SELECT  8, 'GL_LEDGERS', 'OBJECT_TYPE_CODE' FROM dual
    UNION ALL SELECT  9, 'INV_ORGANIZATION_DEFINITIONS_V', 'ORGANIZATION_ID' FROM dual
    UNION ALL SELECT  9, 'INV_ORGANIZATION_DEFINITIONS_V', 'SET_OF_BOOKS_ID' FROM dual
    UNION ALL SELECT 10, 'FA_BOOK_CONTROLS', 'BOOK_TYPE_CODE' FROM dual
    UNION ALL SELECT 10, 'FA_BOOK_CONTROLS', 'SET_OF_BOOKS_ID' FROM dual
),
need_tab AS (
    SELECT n.ord, n.tab FROM need n GROUP BY n.ord, n.tab
),
-- totals for the ord 0 version row (one aggregate per CTE)
need_tab_cnt AS (
    SELECT COUNT(*) AS n FROM need_tab
),
need_col_cnt AS (
    SELECT COUNT(*) AS n FROM need
),
need_obj AS (
    SELECT o.object_name AS tab,
           LISTAGG(o.owner || '.' || o.object_type, ', ')
               WITHIN GROUP (ORDER BY o.owner, o.object_type)   AS visible_as
    FROM   all_objects o
    WHERE  o.object_name IN ( SELECT n.tab FROM need_tab n )
    GROUP  BY o.object_name
),
all_names AS (
    SELECT n.tab FROM need_tab n
),
-- a name that is only a synonym has its columns under the synonym's target
syn AS (
    SELECT s.synonym_name,
           MAX(s.table_name)                         AS target_tab,
           MAX(s.table_owner || '.' || s.table_name) AS target_full
    FROM   all_synonyms s
    WHERE  s.synonym_name IN ( SELECT a.tab FROM all_names a )
    GROUP  BY s.synonym_name
),
cols AS (
    SELECT c.table_name, c.column_name, MAX(c.data_type) AS data_type
    FROM   all_tab_columns c
    WHERE  c.table_name IN ( SELECT a.tab FROM all_names a )
    OR     c.table_name IN ( SELECT s.target_tab FROM syn s )
    GROUP  BY c.table_name, c.column_name
),
tab_has AS (
    SELECT c.table_name FROM cols c GROUP BY c.table_name
),
resolved AS (
    SELECT a.tab,
           CASE WHEN th.table_name IS NOT NULL THEN a.tab ELSE s.target_tab END AS col_tab,
           s.target_full
    FROM        all_names a
    LEFT JOIN   tab_has   th ON th.table_name   = a.tab
    LEFT JOIN   syn       s  ON s.synonym_name  = a.tab
),
need_check AS (
    SELECT  n.ord, n.tab,
            COUNT(*)                                          AS n_needed,
            LISTAGG(CASE WHEN c.column_name IS NULL THEN n.col END, ', ')
                WITHIN GROUP (ORDER BY n.col)                 AS missing,
            LISTAGG(CASE WHEN c.data_type IN ('NVARCHAR2', 'NCHAR', 'NCLOB',
                                              'CLOB', 'BLOB', 'LONG')
                         THEN n.col || ' ' || c.data_type END, ', ')
                WITHIN GROUP (ORDER BY n.col)                 AS type_flags
    FROM        need     n
    JOIN        resolved r ON r.tab = n.tab
    LEFT JOIN   cols     c ON c.table_name = r.col_tab AND c.column_name = n.col
    GROUP   BY  n.ord, n.tab
),
col_lists AS (
    SELECT  c.table_name,
            LISTAGG(c.column_name, ' ' ON OVERFLOW TRUNCATE)
                WITHIN GROUP (ORDER BY c.column_name)         AS col_list
    FROM    cols c
    GROUP   BY c.table_name
),
grid AS (
    SELECT  nc.ord                                                    AS ord,
            CAST(nc.tab AS VARCHAR2(400))                             AS object_name,
            CAST(nc.n_needed || ' needed' AS VARCHAR2(400))           AS needed_count,
            CAST(CASE WHEN r.col_tab IS NULL OR cl.table_name IS NULL
                      THEN '*** OBJECT NOT VISIBLE ***'
                      WHEN nc.missing IS NULL THEN 'ALL OK'
                      ELSE '*** MISSING: ' || nc.missing || ' ***'
                 END AS VARCHAR2(4000))                               AS needed_columns,
            CAST(NVL(nc.type_flags, '-') AS VARCHAR2(4000))           AS type_flags,
            CAST(NVL(nob.visible_as, '-')
                 || CASE WHEN r.col_tab <> nc.tab
                         THEN ' (columns read from ' || r.target_full || ')' END
                 AS VARCHAR2(4000))                                   AS visible_as,
            CAST(NVL(cl.col_list, '-') AS VARCHAR2(4000))             AS columns_present
    FROM        need_check nc
    JOIN        resolved   r  ON r.tab  = nc.tab
    LEFT JOIN   need_obj   nob ON nob.tab = nc.tab
    LEFT JOIN   col_lists  cl ON cl.table_name = r.col_tab
    UNION ALL
    SELECT  0,
            TO_CHAR('V8_0 v1.1 (Section 8 block v1.1)'),
            TO_CHAR(nt.n || ' objects / ' || ncc.n || ' columns needed'),
            TO_CHAR('VERSION ROW: compare this line with the query header'),
            TO_CHAR('-'),
            TO_CHAR('-'),
            TO_CHAR('-')
    FROM    need_tab_cnt nt CROSS JOIN need_col_cnt ncc
)
SELECT  g.ord              AS ord,
        g.object_name      AS object_name,
        g.needed_count     AS needed_count,
        g.needed_columns   AS needed_columns,
        g.type_flags       AS type_flags,
        g.visible_as       AS visible_as,
        g.columns_present  AS columns_present
FROM    grid g
ORDER BY g.ord
